import { AppProvider } from '@/contexts/productcontext'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {CartProvider} from '@/contexts/cartContext'
import { FilterContextProvider } from '@/contexts/filterContext'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <FilterContextProvider>
            <CartProvider>
            {children}
            </CartProvider>
          </FilterContextProvider>
        </AppProvider>
        </body>
    </html>
  )
}
